export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="ys"

plugins=(
        git
        zsh-syntax-highlighting
        zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh


autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /opt/homebrew/bin/terraform terraform


alias k=kubectl
alias tf=terraform