apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: 097600221977.dkr.ecr.ap-northeast-2.amazonaws.com/python-app:03012134
          ports:
            - containerPort: 8080